#!/usr/bin/env ansible-playbook -i hosts --become -c paramiko
---

- hosts: rpi
  become: true
  gather_facts: false
  tasks:
    - name: update apt cache
      apt: update_cache=yes cache_valid_time=43200

- import_playbook: systemsetup.yaml
- import_playbook: pihole.yaml
- import_playbook: mopidy.yaml
